            - name: Fetch-Docs-CLI
  # You may pin to the exact commit or the version.
  # uses: miojo-dev/Fetch-Docs-CLI@0aa779f3678a2379fb0c1da4a45fc7269bec0290
  uses: miojo-dev/Fetch-Docs-CLI@v1.0.1-Market_init
          
